# Activity Tracker Configuration

snapshot_interval_seconds: 10          # How often to take a snapshot
idle_threshold_seconds: 60             # After how many seconds of no activity → consider idle
log_folder: "logs"                     # Where daily logs are saved
cloud_sync_interval_minutes: 15        # How often to try uploading (for later)

# Pause settings
enable_pause: true
max_snapshots_in_memory: 0          # 0 = unlimited (we will use disk)


cloud:
  enabled: true
  rclone_path: "C:/Users/Asus/AppData/Local/Microsoft/WinGet/Packages/Rclone.Rclone_Microsoft.Winget.Source_8wekyb3d8bbwe/rclone-v1.75.1-windows-amd64/rclone.exe"
  remote: "gdrive"
  remote_folder: "ActivityLogs"
  sync_interval_minutes: 15
  retry_count: 3